title: Technical Writer portfolio
description: A test site for my upcoming portfolio
theme: just-the-docs

url: https://sant720.github.io/technical-writer-portfolio/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
